// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdaxr3WflzHZ1masushF2IFQGbybHivV4',
    appId: '1:830741539446:web:75f025582796b1bd760d57',
    messagingSenderId: '830741539446',
    projectId: 'mymacho-8cc53',
    authDomain: 'mymacho-8cc53.firebaseapp.com',
    storageBucket: 'mymacho-8cc53.appspot.com',
    measurementId: 'G-EKGFX9NKG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8fQppduamhMUGU15cvXReis_wUwKEys',
    appId: '1:830741539446:android:8ff5a1e920f38eef760d57',
    messagingSenderId: '830741539446',
    projectId: 'mymacho-8cc53',
    storageBucket: 'mymacho-8cc53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMvk0lm2LEhLk-sDi3XBuFrRVLcmzf9P0',
    appId: '1:830741539446:ios:0a7145e95f2f70ad760d57',
    messagingSenderId: '830741539446',
    projectId: 'mymacho-8cc53',
    storageBucket: 'mymacho-8cc53.appspot.com',
    iosClientId: '830741539446-jvt9r86mh06j68rsr1f90ud6n4mn0akf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMvk0lm2LEhLk-sDi3XBuFrRVLcmzf9P0',
    appId: '1:830741539446:ios:0a7145e95f2f70ad760d57',
    messagingSenderId: '830741539446',
    projectId: 'mymacho-8cc53',
    storageBucket: 'mymacho-8cc53.appspot.com',
    iosClientId: '830741539446-jvt9r86mh06j68rsr1f90ud6n4mn0akf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStarter',
  );
}
